proxy:
  port: 8080
  authentication: simple
  admin-groups: admins
  users:
  - name: Tom
    password: Tom@123
    groups: admins
  - name: Jon
    password: Jon@123
    groups: admins
  - name: Adam
    password: Adam@123
  - name: Guest
    password: Guest@123
  container-backend: kubernetes
  kubernetes:
    internal-networking: true
    url: https://192.168.49.2:8443 
    #cert-path: /home/ubuntu/.minikube/profiles/shiny
    namespace: shiny
    image-pull-policy: IfNotPresent
  specs:
  - id: Telephone_Application
    display-name: Telephones by region
    description: Application which shows telephone by region
    container-cmd: ["R", "-e", "shiny::runApp('/app/Shiny')"]
    container-image: ${registry_name}.azurecr.io/Rshiny-application:latest
  - id: 01_hello
    display-name: Hello Application
    description: Application which demonstrates the basics of a Shiny app
    container-cmd: ["R", "-e", "shinyproxy::run_01_hello()"]
    container-image: openanalytics/shinyproxy-demo
    #container-network: "${proxy.docker.container-network}"
    # container-volumes: ["${proxy.work-directory}/apps:/apps"]
  - id: euler
    display-name: Euler's number
    #container-cmd: ["R", "-e", "shiny::runApp('/root/euler')"]
    container-image: euler:latest
logging:
  file:
    shinyproxy.log