version: "3.6"
services:
  shinyproxy:
    image: sr-shiny
    container_name: dnv_shinyproxy
    restart: on-failure
    entrypoint: "java -jar /app/shinyproxy.jar --spring.config.location=/data/shiny/application.yml"
    networks:
      - dnv-net
    ports:
      - 8080:8080
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
      - ./shinyproxy-logs/server:/log
      - ./shinyproxy-logs/container:/container-logs
      - ./application.yml:/data/shiny/application.yml
networks:
  dnv-net:
    name: dnv-net
