version: "3.6"
services:
  shinyproxy:
    image: shinyproxy
    container_name: dnv_shinyproxy
    restart: on-failure
    networks:
      - dnv-net
    ports:
      - 8080:8080
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
      - ./shinyproxy-logs/server:/log
      - ./shinyproxy-logs/container:/container-logs
networks:
  dnv-net:
    name: dnv-net
