name: Update Spring Boot Version

on:
  workflow_dispatch:
  schedule:
    - cron: '0 12 * * *' # Once per day at 12am UTC

jobs:
    update-spring-boot-version:
      runs-on: ubuntu-latest
      steps:
        - uses: actions/checkout@v3
        - name: Update Spring Boot Version
          run: ./update-spring-boot-version.sh
        - name: Extract Version
          run: echo "MINOR_VERSION=$(cat versions.properties | grep springBootVersion | cut -d'=' -f2)" >> $GITHUB_ENV
        - uses: stefanzweifel/git-auto-commit-action@v4
          with:
            commit_message: "Update Spring Boot Version to ${{ env.MINOR_VERSION }}"
