version: '3.6'
services:
  influxdb:
    image: influxdb:latest
    container_name: influxdb
    restart: always
    environment:
      - INFLUXDB_DB=influx
      - INFLUXDB_ADMIN_USER=admin
      - INFLUXDB_ADMIN_PASSWORD=admin
    ports:
      - '8086:8086'
    volumes:
      - influxdb_data:/var/lib/influxdb
  cache:
    image: redis:latest
    restart: always
    ports:
      - '6379:6379'
    volumes: 
      - cache_data:/data
volumes:
  influxdb_data: {}
  cache_data: {}